from accounts_tests import AccountInternalTests
from apps_tests import PHAInternalTests
from carenets_tests import CarenetInternalTests
from oauth_tests import OauthInternalTests
from records_tests import RecordInternalTests
from reporting_tests import ReportingInternalTests
